### PR TITLE
Allow API host to be overridden with an optional CLI param and use flags instead of positional args.

### PR DESCRIPTION
**Pull request by vlymar**
This PR updates the script to check for a fourth command line parameter. If its present, use that as the API host, otherwise fall back on https://app.launchdarkly.com.

**Edit:** also converts positional args to flags.

### CODE REVIEW

**Comment by pkaeding** [comment]
All of these postional arguments are getting pretty messy. What do you think about changing all of them to [flags](https://www.npmjs.com/package/flags)?

**Comment by vlymar** [comment]
will do

**Comment by pkaeding** [comment]
https://www.npmjs.com/package/commander looks like another similar flags package. No idea which is better.

**Comment by vlymar** [comment]
ready for you to take another look @pkaeding

**Comment by apechimp** [comment]
NOOOOOOOOOOOOOOOOOOOO [yargs](https://www.npmjs.com/package/yargs) is the only acceptable choice for CLI parsing.

Nice work! 👍

**Pull request merged**
